// Del_5_React/Laborationer/Laboration 1/myfirstreactapp/src/components/Navbar.js
import React from 'react'
// vi skickar namn till navbar, funktion login och objekt reader
const Navbar = ({title,login,reader}) => {
    

   
    return (
        <nav className="navbar navbar-expand-lg navbar-light bg-light shadow sticky-top mt-3">
        <div className="container-fluid mx-2">
            <a className="navbar-brand" href="/#">{title}</a>
               

            <button className="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span className="navbar-toggler-icon"></span>
            </button>
            <div className="collapse navbar-collapse" id="navbarNav">
            <ul className="navbar-nav">
                <li className="nav-item">
                <a className="nav-link active" aria-current="page" href="/#">Home</a>
                </li>
                <li className="nav-item">
                <a className="nav-link" href="/#">Features</a>
                </li>
                <li className="nav-item">
                <a className="nav-link" href="/#">Pricing</a>
                </li>
                <li className="nav-item">
                  <button type="button" className="nav-link active btn shadow-none" onClick={login}> {  reader.loggedIn ? reader.name:"Logga in" }</button>                  
                </li>
 
            </ul>

            </div>
            
  </div>
</nav>
    )
}

export default Navbar

// Del_3_Vue/Laborationer/Laboration 5/matsedel/src/components/Navbar.vue
<template>
      <nav class="navbar navbar-expand-md navbar-light bg-light">
      <div class="container-fluid">
        <router-link to="/" class="navbar-brand px-3" ><i class="fas fa-coffee"></i></router-link>

        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav">
              
            <router-link :to="{name:'About'}" class="nav-link px-3" aria-current="page">About us</router-link>
            <router-link :to="{name:'SearchMeals'}" class="nav-link px-3" aria-current="page">Find meals</router-link>
            <router-link :to="{name:'Meals'}" exact class="nav-link px-3" aria-current="page">Meals</router-link>
        
            <router-link :to="{name:'WeekMenu'}" exact class="nav-link px-3" aria-current="page">Week Menu</router-link>
            <router-link :to="{name:'Ingredients'}" exact class="nav-link px-3" aria-current="page">Ingerdients</router-link>
            
            
          </div>
        </div>

      </div>
</nav>

</template>

<script>

export default {
  name : 'Navbar',
  

}
</script>

<style scoped>

.nav-link:hover{
    border-radius: 0.5rem;
    background-color: #b4b4b4;
    border-color: #b4b4b4;;
    
}
.nav-link.router-link-active {
   text-decoration: underline;
}
</style>
